version: 2.1
jobs:
  remix-plugin:
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: node -v
      - run: npm install
      - run: npm run build
      - run: npm run test
      
workflows:
  version: 2
  build_all:
    jobs:
      - remix-plugin
