version: 2
jobs:
  remix-plugin:
    docker:
        - image: circleci/node:20
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test
      
workflows:
  version: 2
  build_all:
    jobs:
      - remix-plugin
